name: FINAL BUILD MAC

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 查看目录（调试用）
        run: ls -R

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install deps
        run: |
          cd amadeus-system-new-mac
          pnpm install --no-frozen-lockfile

      - name: Build
        run: |
          cd amadeus-system-new-mac
          pnpm build

      - name: Build dmg
        run: |
          cd amadeus-system-new-mac
          npx electron-builder --mac dmg --arm64

      - name: Upload dmg
        uses: actions/upload-artifact@v4
        with:
          name: mac-dmg
          path: amadeus-system-new-mac/dist/*.dmg
